<!DOCTYPE html>
<!--Converted via md-to-html-->
<html>
 <head>
<link rel="stylesheet" type="text/css" href="../main.css">
 </head>
 <body>
  <h1>
   Why should I have written ZeroMQ in C, not C++ (part I)
  </h1>
  <p>
   Just to be clear from the very beginning: This is not going to be a Torvalds-ish rant against C++ from the point of view of die-hard C programmer.
  </p>
  <p>
   I've been using C++ whole my professional career and it's still my language of choice when doing most projects.
  </p>
  <p>
   Naturally, when I started ZeroMQ project back in 2007, I've opted for C++. The main reasons were:
  </p>
  <ol>
   <li>
    Library of data structures and algorithms (STL) is part of the language. With C I would have to either depend on a 3rd party library or had to write basic algorithms of my own in 1970's manner.
   </li>
  </ol>
  <ol>
   <li>
    C++ enforces some basic consistency in the coding style. For example, having the implicit 'this' parameter doesn't allow to pass pointer to the object being worked on using several disparate mechanisms as it often happens to be the case with C projects. Same applies to explicit marking of member variables as private and many other features of the language.
   </li>
  </ol>
  <ol>
   <li>
    This point is actually a subset of the previous one, but it's worth of explicit mention: Implementing virtual functions in C is pretty complex and tends to be slightly different for each class which makes understanding and managing the code a pain.
   </li>
  </ol>
  <ol>
   <li>
    And finally: Everybody loves destructors being invoked automatically at the end of the block.
   </li>
  </ol>
  <p>
   Now, almost 5 years later, I would like to publicly admit that using C++ was a poor choice and explain why I believe it is so.
  </p>
  <p>
   First, it's important to take into account that ZeroMQ was intended to be a piece of infrastructure with continuous uptime. It should never fail and never exhibit undefined behaviour. Thus, the error handling was of utmost importance. It had to be very explicit and unforgiving.
  </p>
  <p>
   C++ exceptions just didn't fill the bill. They are great for guaranteeing that program doesn't fail — just wrap the main function in try/catch block and you can handle all the errors in a single place.
  </p>
  <p>
   However, what's great for avoiding straightforward failures becomes a nightmare when your goal is to guarantee that no undefined behaviour happens. The decoupling between raising of the exception and handling it, that makes avoiding failures so easy in C++, makes it virtually impossible to guarantee that the program never runs info undefined behaviour.
  </p>
  <p>
   With C, the raising of the error and handling it are tightly couped and reside at the same place in the source code. This makes it easy to understand what happens if error happens:
  </p>
  <pre><code>int rc = fx ();
</code></pre>
  <pre><code>if (rc != 0)
</code></pre>
  <pre><code>    handle_error ();
</code></pre>
  <p>
   With C++ you just throw the error. What happens then is not at all obvious:
  </p>
  <pre><code>int rc = fx ();
</code></pre>
  <pre><code>if (rc != 0)
</code></pre>
  <pre><code>    throw std::exception ();
</code></pre>
  <p>
   The problem with that is that you have no idea of who and where is going to handle the exception. As long as the handling code is in the same function the error handling often remains more of less sane although not very readable:
  </p>
  <pre><code>try {
</code></pre>
  <pre><code>    ...
</code></pre>
  <pre><code>    int rc = fx ();
</code></pre>
  <pre><code>    if (rc != 0)
</code></pre>
  <pre><code>        throw std::exception ("Error!");
</code></pre>
  <pre><code>    ...
</code></pre>
  <pre><code>catch (std::exception &amp;e) {
</code></pre>
  <pre><code>    handle_exception ();
</code></pre>
  <pre><code>}
</code></pre>
  <p>
   However, consider what happens when there are two different errors thrown in the same function:
  </p>
  <pre><code>class exception1 {};
</code></pre>
  <pre><code>class exception2 {};
</code></pre>
  <pre><code>try {
</code></pre>
  <pre><code>    ...
</code></pre>
  <pre><code>    if (condition1)
</code></pre>
  <pre><code>        throw my_exception1 ();
</code></pre>
  <pre><code>    ...
</code></pre>
  <pre><code>    if (condition2)
</code></pre>
  <pre><code>        throw my_exception2 ();
</code></pre>
  <pre><code>    ...
</code></pre>
  <pre><code>}
</code></pre>
  <pre><code>catch (my_exception1 &amp;e) {
</code></pre>
  <pre><code>    handle_exception1 ();
</code></pre>
  <pre><code>}
</code></pre>
  <pre><code>catch (my_exception2 &amp;e) {
</code></pre>
  <pre><code>    handle_exception2 ();
</code></pre>
  <pre><code>}
</code></pre>
  <p>
   Compare that to its C equivalent:
  </p>
  <pre><code>...
</code></pre>
  <pre><code>if (condition1)
</code></pre>
  <pre><code>   handle_exception1 ();
</code></pre>
  <pre><code>...
</code></pre>
  <pre><code>if (condition2)
</code></pre>
  <pre><code>   handle_exception2 ();
</code></pre>
  <pre><code>...
</code></pre>
  <p>
   It's far more readable and — as a bonus — compiler is likely to produce more efficient code.
  </p>
  <p>
   However, it doesn't end there. Consider the case when the exception is not handled in the function that raises it. In such case the handling of the error can happen anywhere, depending on where the function is called from.
  </p>
  <p>
   While the possibility to handle the exceptions differently in different contexts may seem appealing at the first sight, it quickly turns into a nightmare.
  </p>
  <p>
   As you fix individual bugs you'll find out that you are replicating almost the same error handling code in many places. Adding a new function call to the code introduces that possibility that different types of exceptions will bubble up to the calling function where there are not yet properly handled. Which means new bugs.
  </p>
  <p>
   If you don't give up on the "no undefined behaviour" principle, you'll have to introduce new exception types all the time to distinguish between different failure modes. However, adding a new exception type means that it can bubble up to different places. Pieces of code have to be added to all those places, otherwise you end up with undefined behaviour.
  </p>
  <p>
   At this point you may be screaming: That's what exception specifications are for!
  </p>
  <p>
   Well, the problem is that exception specifications are just a tool to handle the problem of exponential growth of the exception handling code in a more systematic manner, but it doesn't solve the problem itself. It can even be said it makes it worse as now you have to write code for the new exception types, new exception handling code *and* new exception specifications.
  </p>
  <p>
   Taking the problems described above into account I've decided to use C++ minus exceptions. That's exactly how ZeroMQ and Crossroads I/O looks like today.
  </p>
  <p>
   Unfortunately, the problems don't end up here…
  </p>
  <p>
   Consider what happens when initialisation of an object can fail. Constructors have no return values, so failure can be reported only by throwing an exception. However, I've decided not to use exceptions. So we have to go for something like this:
  </p>
  <pre><code>class foo
</code></pre>
  <pre><code>{
</code></pre>
  <pre><code>public:
</code></pre>
  <pre><code>    foo ();
</code></pre>
  <pre><code>    int init ();
</code></pre>
  <pre><code>    ...
</code></pre>
  <pre><code>};
</code></pre>
  <p>
   When you create an instance of the class, constructor is called (which cannot fail) and then you explicitly call init function (which can fail).
  </p>
  <p>
   This is more complex that what you would do with C:
  </p>
  <pre><code>struct foo
</code></pre>
  <pre><code>{
</code></pre>
  <pre><code>    ...
</code></pre>
  <pre><code>};
</code></pre>
  <pre><code>int foo_init (struct foo *self);
</code></pre>
  <p>
   However, the really bad thing about the C++ version of the code is what happens when developers put some actual code into the constructor instead of systematically keeping the constructors empty.
  </p>
  <p>
   If that's the case a special new object state comes into being. It's the 'semi-initialised' state when object has been constructed but init function haven't been called yet. The object (and specifically the destructor) should be modified in such a way as to decently handle the new state. Which in the end means adding new condition to every method.
  </p>
  <p>
   Now you say: But that's just a consequence of your artificial restriction of not using exceptions! If exception is thrown in a constructor, C++ runtime cleans the object as appropriate and there is no 'semi-initalised' state whatsoever!
  </p>
  <p>
   Fair enough. However, it's beside the point. If you start using exceptions you have to handle all the exception-related complexity as described in the beginning. And that is not a reasonable option for an infrastructure component with the need to be very robust in the face of failures.
  </p>
  <p>
   Moreover, even if initialisation wasn't a problem, termination definitely is. You can't really throw exceptions in the destructor. Not because of some self-imposed artificial restrictions but because if the destructor is invoked in the process or unwinding the stack and it happens to throw an exception, it crashes the entire process.
  </p>
  <p>
   Thus, if termination can fail, you need two separate functions to handle it:
  </p>
  <pre><code>class foo
</code></pre>
  <pre><code>{
</code></pre>
  <pre><code>public:
</code></pre>
  <pre><code>    ...
</code></pre>
  <pre><code>    int term ();
</code></pre>
  <pre><code>    ~foo ();
</code></pre>
  <pre><code>};
</code></pre>
  <p>
   Now we are back to the problem we've had with the initialisation: There's a new 'semi-terminated' state that we have to handle somehow, add new conditions to individual member functions etc.
  </p>
  <pre><code>class foo
</code></pre>
  <pre><code>{
</code></pre>
  <pre><code>public:
</code></pre>
  <pre><code>    foo () : state (semi_initialised)
</code></pre>
  <pre><code>    {
</code></pre>
  <pre><code>         ...
</code></pre>
  <pre><code>    }
</code></pre>
  <pre><code>    int init ()
</code></pre>
  <pre><code>    {
</code></pre>
  <pre><code>        if (state != semi_initialised)
</code></pre>
  <pre><code>            handle_state_error ();
</code></pre>
  <pre><code>        ...
</code></pre>
  <pre><code>        state = intitialised;
</code></pre>
  <pre><code>    }
</code></pre>
  <pre><code>    int term ()
</code></pre>
  <pre><code>    {
</code></pre>
  <pre><code>         if (state != initialised)
</code></pre>
  <pre><code>             handle_state_error ();
</code></pre>
  <pre><code>         ...
</code></pre>
  <pre><code>         state = semi_terminated;
</code></pre>
  <pre><code>    }
</code></pre>
  <pre><code>    ~foo ()
</code></pre>
  <pre><code>    {
</code></pre>
  <pre><code>         if (state != semi_terminated)
</code></pre>
  <pre><code>             handle_state_error ();
</code></pre>
  <pre><code>         ...
</code></pre>
  <pre><code>    }
</code></pre>
  <pre><code>    int bar ()
</code></pre>
  <pre><code>    {
</code></pre>
  <pre><code>         if (state != initialised)
</code></pre>
  <pre><code>             handle_state_error ();
</code></pre>
  <pre><code>         ...
</code></pre>
  <pre><code>    }
</code></pre>
  <pre><code>};
</code></pre>
  <p>
   Compare the above to the C implementation. There are only two states. Not initialised object/memory where all the bets are off and the structure can contain random data. And there is initialised state, where the object is fully functional. Thus, there's no need to incorporate a state machine into the object:
  </p>
  <pre><code>struct foo
</code></pre>
  <pre><code>{
</code></pre>
  <pre><code>    ...
</code></pre>
  <pre><code>};
</code></pre>
  <pre><code>int foo_init ()
</code></pre>
  <pre><code>{
</code></pre>
  <pre><code>    ...
</code></pre>
  <pre><code>}
</code></pre>
  <pre><code>int foo_term ()
</code></pre>
  <pre><code>{
</code></pre>
  <pre><code>    ...
</code></pre>
  <pre><code>}
</code></pre>
  <pre><code>int foo_bar ()
</code></pre>
  <pre><code>{
</code></pre>
  <pre><code>    ...
</code></pre>
  <pre><code>}
</code></pre>
  <p>
   Now consider what happens when you add inheritance to the mix. C++ allows to initialise base classes as a part of derived class' constructor. Throwing an exception will destruct the parts of the object that were already successfully initialised:
  </p>
  <pre><code>class foo : public bar
</code></pre>
  <pre><code>{
</code></pre>
  <pre><code>public:
</code></pre>
  <pre><code>    foo () : bar () {}
</code></pre>
  <pre><code>    ...
</code></pre>
  <pre><code>};
</code></pre>
  <p>
   However, once you introduce separate init functions, the number of states starts to grow. In addition to uninitialised, semi-initialised, initialised and semi-terminated states you encounter combinations of the states. As an example you can imagine a fully initialised base class with semi-initialised derived class.
  </p>
  <p>
   With objects like these it's almost impossible to guarantee predictable behaviour. There's a lot of different combinations of semi-initialised and semi-terminated parts of the object and given that failures that cause them are often very rare the most of the related code probably goes into the production untested.
  </p>
  <p>
   To summarise the above, I believe that requirement for fully-defined behaviour breaks the object-oriented programming model. The reasoning is not specific to C++. It applies to any object-oriented language with constructors and destructors.
  </p>
  <p>
   Consequently is seems that object-oriented languages are better suited for the environments where the need for rapid development beats the requirement for no undefined behaviour.
  </p>
  <p>
   There's no silver bullet here. The systems programming will have to live on with C.
  </p>
  <p>
   By the way, I've started experimenting with translating ZeroMQ into C lately. The code looks great!
  </p>
  <p>
   EDIT: The endeavour evolved into a new project called
   <em>
    nanomsg
   </em>
   in the meantime. Check it
   <a href="http://nanomsg.org">
    here
   </a>
   .
  </p>
  <p>
   Read
   <a href="/blog:8">
    part II of the article
   </a>
   .
  </p>
  <p>
   <strong>
    May 10th, 2012
   </strong>
  </p>
 </body>
</html>